--- #YAML:1.0
name:               Test-VariousBits
version:            2
abstract:           Various test helpers.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5
    Test:  0
    vars:  0
resources:
    homepage:  http://user42.tuxfamily.org/test-variousbits/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - xt
        - devel
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            base:                0
            Data::Dumper:        0
            Devel::Comments:     0
            File::Spec:          0
            FindBin:             0
            Parse::CPAN::Meta:   0
            Pod::Simple::HTML:   0
            Scalar::Util:        0
            Smart::Comments:     0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::YAML::Meta:    0.15
            warnings::unused:    0
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
    maximum_interoperation:
        description:  Have maximum inter-operation with other modules.
        requires:
            Sub::Delete:  0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            IPC::SysV:            0
            Module::Mask:         0
            Module::Util:         0
            Scalar::Util:         0
            Test::Without::Module:  0
